backend:
  name: github
  repo: tankcaster/new-hope-church
media_folder: static/assets
public_folder: /assets
collections:
  - name: events
    label: Events
    folder: src/md/events
    create: true
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "event" }
      - { name: start, label: Start, widget: date }
      - { name: end, label: End, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Desription, widget: text }
      - { name: image, label: Image, widget: image }
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - file: src/md/pages/index.md
        label: Landing Page
        name: index
        fields:
          - {
              label: "Type",
              name: "type",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Service Times,
              name: times,
              widget: object,
              fields:
                [
                  {
                    label: Sunday Service Times,
                    name: sundayTimes,
                    widget: list,
                  },
                  {
                    label: Wednesday Service Times,
                    name: wednesdayTimes,
                    widget: list,
                  },
                ],
            }
          - {
              label: Contact Info,
              name: contact,
              widget: object,
              fields:
                [
                  { label: Address, name: address, widget: string },
                  { label: Phone, name: phone, widget: string },
                  { label: Email, name: email, widget: string },
                ],
            }
