backend:
  name: github
  repo: tankcaster/new-hope-church
media_folder: static/assets
public_folder: /assets
collections:
  - name: events
    label: Events
    folder: src/md/events
    create: true
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "event" }
      - { name: start, label: Start, widget: date }
      - { name: end, label: End, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Desription, widget: text }
      - { name: image, label: Image, widget: image }
  - name: news
    label: News
    folder: src/md/news
    create: true
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "news" }
      - { label: "Published", name: "published", widget: "datetime" }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Image, widget: image }
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - file: src/md/pages/about.md
        label: About Page
        name: about
        fields:
          - {
              label: "Type",
              name: "type",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Body, name: body, widget: markdown }
  - name: info
    label: Info
    editor:
      preview: false
    files:
      - file: src/md/info/times.md
        label: Service Times
        name: service-times
        fields:
          - { label: Type, name: type, widget: hidden, default: service-times }
          - { label: Sunday Times, name: sunday-times, widget: list }
          - { label: Wednesday Times, name: wednesday-times, widget: list }
      - file: src/md/info/contact.md
        label: Contact Info
        name: contact
        fields:
          - { label: Type, name: type, widget: hidden, default: contact-info }
          - { label: Address, name: address, widget: string }
          - { label: Phone, name: phone, widget: number }
          - { label: Email, name: email, widget: string }
